### ISSUE TITLE
Villager pie chart on Villager Distribution

### ISSUE THREAD

**Issue by Coow** [SichYuriy/aoe4-production-calculator#3]
Add a visual representation next to the Villager Distribution similar to the Age of Mythology
![image](https://github.com/user-attachments/assets/56b48e11-e2ec-4d3e-b733-6b3f232f1734)

**Comment by SichYuriy** [comment]
I will not do it. I do not see its purpose.
Cons:
- it may be misleading in the early game. This tool most helpful for early-game
- it takes screen place
